version: '3'
services:
  auth-service:
    build:
      context: ./user-auth-microservice
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - '3000:3000'
    networks:
      - container-net

  blog-service:
    build:
      context: ./blog-post-microservice
      dockerfile: Dockerfile
    container_name: blog-service
    ports:
      - '9090:9090'
    networks:
      - container-net

networks:
  container-net:
    driver: bridge
